apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata: {name: loadbalancers.vmware.com}
spec:
  group: vmware.com
  names:
    kind: LoadBalancer
    plural: loadbalancers
    shortNames: [lb]
    singular: loadbalancer
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema: {type: object, x-kubernetes-preserve-unknown-fields: true}
    served: true
    storage: true
