apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: ncp-exec-role-binding, namesapce: nsx-system}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: ncp-exec-role}
subjects:
- {kind: ServiceAccount, name: ncp-svc-account, namespace: nsx-system}
