apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: {name: ncp-psp-cluster-role}
rules:
- apiGroups: [policy]
  resourceNames: [ncp-psp]
  resources: [podsecuritypolicies]
  verbs: [use]
