apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata: {name: ncp-psp}
spec:
  defaultAddCapabilities: null
  fsGroup:
    ranges:
    - {max: 65535, min: 1}
    rule: MustRunAs
  hostIPC: false
  hostNetwork: true
  hostPID: false
  privileged: false
  readOnlyRootFilesystem: false
  requiredDropCapabilities: [KILL]
  runAsUser: {rule: RunAsAny}
  seLinux: {rule: RunAsAny}
  supplementalGroups:
    ranges:
    - {max: 65535, min: 1}
    rule: MustRunAs
  volumes: [configMap, downwardAPI, emptyDir, persistentVolumeClaim, projected, secret]
