apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: {name: nsx-node-agent-psp-cluster-role-binding}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: nsx-node-agent-psp-cluster-role}
subjects:
- {kind: ServiceAccount, name: nsx-node-agent-svc-account, namespace: nsx-system}
