apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata: {name: nsxlbmonitors.vmware.com}
spec:
  group: vmware.com
  names:
    kind: NSXLoadBalancerMonitor
    plural: nsxlbmonitors
    shortNames: [lbm]
    singular: nsxlbmonitor
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema: {type: object, x-kubernetes-preserve-unknown-fields: true}
    served: true
    storage: true
