apiVersion: operator.nsx.vmware.com/v1
kind: NcpInstall
metadata:
  name: ncp-install
  namespace: nsx-system-operator
spec:
  ncpReplicas: 1
  addNodeTag: false
  nsx-ncp:
    # Uncomment below to add specific nodeSelector for nsx-ncp component
    #nodeSelector:
      #<node_label_key>: <node_label_value>
